version: "3.7"

# This file has two versions of the app
# One for dev and one for prod
# Everything is managed by control.sh - so please use that rather than calling docker-compose manually
# Main differences for the dev version are
# - Only one port is exposed since we don't need to scale in dev mode
# - The local scovid/ directory is mounted to scovid/ in the container for easy editing

volumes:
  data:

services:
  # Prod version of our app
  app:
    build: .
    container_name: 'scovid'
    restart: always
    ports:
      - 5000-5001:5000
    volumes:
      - data:/home/code/scovid19/data
    environment:
      ENV: prod
      SCOVID_PROJECT_ROOT: /home/code/scovid19/
      SCOVID_TWITTER_API_KEY: ${SCOVID_TWITTER_API_KEY}
      SCOVID_TWITTER_API_SECRET: ${SCOVID_TWITTER_API_SECRET}
      SCOVID_TWITTER_ACCESS_TOKEN: ${SCOVID_TWITTER_ACCESS_TOKEN}
      SCOVID_TWITTER_ACCESS_SECRET: ${SCOVID_TWITTER_ACCESS_SECRET}

  # Dev version of our app
  app-dev:
    build: .
    container_name: 'scovid'
    restart: always
    ports:
      - 5000:5000
    volumes:
      - './scovid:/home/code/scovid19/scovid'
      - data:/home/code/scovid19/data
    environment:
      ENV: dev
      SCOVID_PROJECT_ROOT: /home/code/scovid19/
