name: Formatting - Prettier

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      master

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: 'Run prettier'
        uses: creyD/prettier_action@v3.1
        with:
          prettier_options: --write **.html **.js **.css

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: :art: Auto-format with prettier
