name: Formatting - Prettier

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      master

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Run prettier check'
        run: |
          npm i -g prettier
          prettier --check **.html **.js **.css

