name: Test

on: [push, pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Run pytest'
        run: |
          ./control.sh --docker up
          docker exec scovid pytest
